//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weeho.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    
    using Weeho.Model;
    public partial class SysAction:IEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SysAction()
        {
            this.SysRoleAction = new HashSet<SysRoleAction>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ActionCode { get; set; }
        public string ActionIcon { get; set; }
        public string ActionTitle { get; set; }
        public int IsShow { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public byte[] RowVersion { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysRoleAction> SysRoleAction { get; set; }
    }
}
