//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weeho.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    
    using Weeho.Model;
    public partial class SysAdmin:IEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SysAdmin()
        {
            this.SysAdminRole = new HashSet<SysAdminRole>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public System.DateTime LastLoginTime { get; set; }
        public string LastLoginIp { get; set; }
        public bool IsAdmin { get; set; }
        public bool Enabled { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public byte[] RowVersion { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysAdminRole> SysAdminRole { get; set; }
    }
}
