//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weeho.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    
    using Weeho.Model;
    public partial class Users:IEntity
    {
        public int Id { get; set; }
        public string NickName { get; set; }
        public string RealName { get; set; }
        public string VerificationCode { get; set; }
        public Nullable<System.DateTime> BirthAge { get; set; }
        public int sex { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public int IsCertification { get; set; }
        public int UserType { get; set; }
        public string IdCard { get; set; }
        public string HeadImg { get; set; }
        public string MemberNumber { get; set; }
        public string bgpic { get; set; }
        public string Career { get; set; }
        public int Level { get; set; }
        public int integral { get; set; }
        public string Qrcode { get; set; }
        public bool IsInfo { get; set; }
        public string linkren { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
